### ISSUE TITLE
Check convergence of heat load on specific wall flag

### ISSUE THREAD

**Issue by linvelgal** [ascot4fusion/ascot5#116]
Improve the plotwall_convergence tool to also calculate and plot the convergence of the heat load on a specific item on the wall marked by a flag.

**Comment by linvelgal** [comment]
@miekkasarki I think this is done. Should I request the merge now so you can check it?

**Comment by miekkasarki** [comment]
Thank you for the contribution! I can take care of the pull-request and merging (this will be part of the next release).

Two things that I'd like to change if that's ok for you (I can make the changes). Instead of `heatloadonflag` and `averagedheatloadonflag`, the function will only include those walltiles defined by `flag` (all wall tiles are included if `flag` is None). This way you can also get `peakload` and `lostpower` only on those tiles specified by `flag`.

The other change is that I don't think a sum of wall loads (in units of W/m^2) is a meaningful quantity (or at least I don't know where it would be useful). I'd drop that and keep only the mean heat load.

**Comment by linvelgal** [comment]
Sure, that all makes sense :) Thank you!

**Comment by miekkasarki** [comment]
Merged.
