### ISSUE TITLE
a5editoptions rejects float values for the distribution charge bin edges

### ISSUE THREAD

**Issue by Ian-Dolby** [ascot4fusion/ascot5#118]
When I set `DIST_MIN_CHARGE=1.5`,   `DIST_MAX_CHARGE=2.5`,    `DIST_NBIN_CHARGE=1` as shown in the [distributions tutorial](https://ascot4fusion.github.io/ascot5/tutorials/distributions.html), the program actually runs with `DIST_MIN_CHARGE=1`,   `DIST_MAX_CHARGE=2`,    `DIST_NBIN_CHARGE=1`. 
This seems to mean that when I run the created file in gyro-orbit mode, the resulting distributions are empty, which I assume is because the tutorial uses alpha particles with a charge of 2 and this is outside the range set by these values. (The run in GC mode behaves correctly).

If I set `DIST_MIN_CHARGE=1.5`,   `DIST_MAX_CHARGE=2.5`,    `DIST_NBIN_CHARGE=1` directly via a5editoptions, it returns an error about non-integer values. I can work around this issue by using `DIST_MIN_CHARGE=1`,   `DIST_MAX_CHARGE=3`,    `DIST_NBIN_CHARGE=1`, but I don't see a way to use a single bin of width 1 which is centred on an integer.

**Comment by miekkasarki** [comment]
I think the tutorial is out of date. Setting `DIST_MIN_CHARGE=1` and `DIST_MAX_CHARGE=3` should be the way to go (as fractional charges could be confusing). The edge limits should be exclusive, so that the bin width is still effectively 1. The post-processing tools only care about the bin value which in both cases is q=2.

Let's keep this issue open until the tutorial has been updated and a proper exception is raised when trying to set fractional values.

**Comment by miekkasarki** [comment]
Tutorials are now updated.
